### ISSUE TITLE
DWMBlurGlass crashes sometimes on "Save As" dialogs

### ISSUE THREAD

**Issue by AdityaKKhullar** [ImSwordQueen/Win10to7Issues#5]
Hi, I have been using this pack since yesterday and while the work is commendable because this is mostly an accurate transformation, there is one major issue with DWMBlurGlass.

I've seen this crashing whenever there have been any "Save As" dialogs in any software, including downloading from a browser using torrents/IDM. I have no idea what is causing this, this is the dialog it is throwing:

![image](https://github.com/ImSwordQueen/Win10to7Issues/assets/72785876/3cc9db98-90c3-4441-940a-06c66ba77aa5)

Also, another issue, whenever you reboot the system, the transparency in the taskbar for some reason is almost 0, however after changing to any theme results in a fix. 

Thanks :)

**Comment by ImSwordQueen** [comment]
The version of DWMBlurGlass i used in 21H2to7 was a beta with button glow that has a crash problem. I uploaded a version of the pack with an older version of DWMBG without caption glow that should resolve the issue which you can find here: https://mega.nz/folder/xmgAgBZS#Qr5FgzEW-ZkT6WJVlnq4zg . The alternative is to replace the version of DWMBG found in C:\Windows\DWMBlurGlass with the releases one [here](https://github.com/Maplespe/DWMBlurGlass).

Meanwhile the other issue is still caused by DWMBlurGlass but with the "Override AccentBlur effect" option as reported in the DWMBlurGlass repo [here](https://github.com/Maplespe/DWMBlurGlass/issues/329).

When DWMBlurGlass's devs make a new update that fixes those issues i will update the pack to include the new version.
