### ISSUE TITLE
Regarding ClassicLogonHook

### ISSUE THREAD

**Issue by aliasmaychange** [ImSwordQueen/Win10to7Issues#85]
I had ClassicLogonHook before I upgraded to a build which included ClassicLogonHook, I left the logon option unchecked when I did, is it intentional that as soon as I check the Embedded POSReady 7 option for branding it changes bitmaps to correspond to said branding? And on another note, why does the pack revert the settings as soon as I pick any other option (picked Windows 10 branding, CLH says Windows 7 Ultimate, note that I still had the logon option unchecked in the installer)?

**Comment by ImSwordQueen** [comment]
Responded on discord but keeping a response here:

The option to install CLH only installs the files. if you have CLH installed and select posready branding it would take the CLH dll and modify it like it would do when you install CLH. Meanwhile the 10 branding does not get applied because the 10 branding is in CLH itself and not in the branding.
